### ISSUE TITLE
Code highlight is not properly supported

### ISSUE THREAD

**Issue by varundey** [lukas-h/lukas-h.github.io#3]
While deploying on github-pages, it concatenates the code. I used the `bash` syntax highlighter for which it didn't work

**Comment by lukas-h** [comment]
Looks like a new to-do. Thank you for the idea! 

Just found this:
https://demisx.github.io/jekyll/2014/01/13/improve-code-highlighting-in-jekyll.html

**Comment by varundey** [comment]
Would be awesome if GitHub styled markdown code highlighting is supported instead of liquid markup.

**Comment by lukas-h** [comment]
Do you know, how to do that? Is there a Jekyll plugin or something like this?

**Comment by varundey** [comment]
You might want to check [this](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0)

**Comment by whileLooper** [comment]
@lukas-h yep, adding single stylesheet is temperate solution for me so far

**Comment by lukas-h** [comment]
looks like it's done :smile:  Thank you for using your time to make it a lot better @varundey

**Comment by lukas-h** [comment]
@varundey I saw the nice improvements of the bottom link bar in your website https://varundey.me/. Do you want to make a pull request that all can have this nice feature?

**Comment by varundey** [comment]
@lukas-h I was just thinking the about it. Created a [pull request](https://github.com/lukas-h/lukas-h.github.io/pull/9). Cheers :+1:

**Comment by lf-araujo** [comment]
Dear @varundey since this issue was closed, your blog has much nicer code highlighting. Would you share the changes you made to your syntax.css? 

Best,

**Comment by varundey** [comment]
@lf-araujo, a lot has changed over the year. You can take the reference from #5, #6 and #7.
